# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DATA_DIR": "10_datascience.ipynb",
         "to_int": "00_common.ipynb",
         "ints": "00_common.ipynb",
         "flatten": "05_norvig.ipynb",
         "reverse_dict": "00_common.ipynb",
         "zippify": "00_common.ipynb",
         "list_multiply": "00_common.ipynb",
         "arr_to_dict": "01_grid.ipynb",
         "neighbors": "01_grid.ipynb",
         "arr_neighbors": "01_grid.ipynb",
         "iterate": "01_grid.ipynb",
         "dimensions": "01_grid.ipynb",
         "Dim": "01_grid.ipynb",
         "positive": "01_grid.ipynb",
         "manhattan": "01_grid.ipynb",
         "conv1d": "01_grid.ipynb",
         "conv2d": "01_grid.ipynb",
         "bfs": "02_maze.ipynb",
         "dijkstra": "02_maze.ipynb",
         "get_path": "02_maze.ipynb",
         "dfs": "02_maze.ipynb",
         "factors": "03_math.ipynb",
         "gcd": "03_math.ipynb",
         "lcm": "03_math.ipynb",
         "md5": "04_special.ipynb",
         "binarysearch": "04_special.ipynb",
         "deduce_matches": "04_special.ipynb",
         "find_pattern_in_iter": "04_special.ipynb",
         "find_repeat": "04_special.ipynb",
         "find_cycle": "04_special.ipynb",
         "data": "05_norvig.ipynb",
         "do": "05_norvig.ipynb",
         "quantify": "05_norvig.ipynb",
         "first": "05_norvig.ipynb",
         "rest": "05_norvig.ipynb",
         "multimap": "05_norvig.ipynb",
         "atom": "05_norvig.ipynb",
         "atoms": "05_norvig.ipynb",
         "list_atoms": "05_norvig.ipynb",
         "dotproduct": "05_norvig.ipynb",
         "mapt": "05_norvig.ipynb",
         "cat": "05_norvig.ipynb",
         "CFG": "06_context_free_grammar.ipynb",
         "left_associative": "07_shunting_yard.ipynb",
         "ShuntingYard": "07_shunting_yard.ipynb",
         "untar_data": "10_datascience.ipynb",
         "timeit": "10_datascience.ipynb",
         "load": "10_datascience.ipynb",
         "save": "10_datascience.ipynb",
         "nan_inspect": "10_datascience.ipynb"}

modules = ["common.py",
           "grid.py",
           "maze.py",
           "math.py",
           "special.py",
           "aoc.py",
           "datascience.py"]

doc_url = "https://jvanelteren.github.io/aocutils/"

git_url = "https://github.com/jvanelteren/aocutils/tree/main/"

def custom_doc_links(name): return None
